branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.cache/yarn'

before_install:
  - nvm install v8.11.0
  - nvm use
  - npm install
  - npm install -g yarn
  - yarn

matrix:
  include:
    - stage: deploy
      language: android
      jdk: oraclejdk8
      cache:
        directories:
          - '$HOME/.gradle/caches/2.8'
          - '$HOME/.gradle/caches/jars-1'
          - '$HOME/.gradle/daemon'
          - '$HOME/.gradle/native'
          - '$HOME/.gradle/wrapper'
          - '$TRAVIS_BUILD_DIR/tmp'
      install:
        - yes | $ANDROID_HOME/tools/bin/sdkmanager "build-tools;27.0.3"
      android:
        components:
          - tools
          - build-tools-23.0.1
          - android-23
          - platform-tools
          - extra-android-m2repository
          - extra-google-google_play_services
          - extra-google-m2repository
          - addon-google_apis-google-16
          - extra-android-support
      script:
        - yarn deploy -t main-app --android
